name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          npm run build
          # Create necessary directories
          mkdir -p out/_next/static
          # Copy static files from .next to out
          cp -r .next/static/* out/_next/static/
          # Copy public files
          cp -r public/* out/ || true
          # Ensure all files are in the correct location
          find out -type f -name "*.js" -exec sed -i 's|/_next/|/portfolio/_next/|g' {} +
          find out -type f -name "*.css" -exec sed -i 's|/_next/|/portfolio/_next/|g' {} +
          find out -type f -name "*.html" -exec sed -i 's|/_next/|/portfolio/_next/|g' {} +
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 